### ISSUE TITLE
Error: Could not open device hw:PCH: denied permission

### ISSUE THREAD

**Issue by vdebuen** [StarAurryon/lpedit#3]
Hello

I've installed Go, therecipe/qt and release_0.4.tar.gz, but when I run ./lpedit and try to select pedal device system show this error message. 

Thanks!
![lpedit_error_01](https://user-images.githubusercontent.com/1242208/106360360-4ac93f80-6318-11eb-9988-a7e0bb9142ad.png)

**Comment by vdebuen** [comment]
If I run ./lpedit with sudo then program hangs up

![lpedit_error_02](https://user-images.githubusercontent.com/1242208/106360520-143ff480-6319-11eb-9db4-7189c5033561.png)

**Comment by StarAurryon** [comment]
Hello vdebuen,

I hope you are doing well. 
You should see your PODHD500X in the list, please select it to make it work. If not please send me a lsusb as a starter.

Aurryon

**Comment by vdebuen** [comment]
Thank you very much, I now have the hw:PODHD500X and the program works perfectly. I suppose it could have been something as silly as the cable not being plugged in correctly because I use a USB extension cable as the computer is a bit far from the pedalboard. The temporary solution has been to use tape to prevent it from coming loose.

Sorry for my clumsiness!

**Comment by StarAurryon** [comment]
No worry. Happy to help.
