### ISSUE TITLE
Duplicate LockData definition

### ISSUE THREAD

**Issue by nemasket** [StarAurryon/lpedit#4]
I was very excited to find this project.  I installed the Go environment and the QT mods per the README files.  

First I did the qt stuff for the Linux environment:

export GO111MODULE=off; go get -v github.com/StarAurryon/qt/cmd/... && $(go env GOPATH)/bin/qtsetup test && $(go env GOPATH)/bin/qtsetup -test=false

This builds and tests successfully.  Then I followed up with:

jurgen@danglard:~$ go get -v github.com/StarAurryon/lpedit 

</br>
Running that yields this error message:

github.com/StarAurryon/lpedit-lib/model/pod
<literal># github.com/StarAurryon/lpedit-lib/model/pod<literal>
go/src/github.com/StarAurryon/lpedit-lib/model/pod/interfaces.go:38:5: duplicate method LockData

I get the same error running main.go directly from the source.  

The go environment is completely new to me and I am drilling down into various things to discover what could be wrong with the steps I have taken.  

I see the project is on hold, but in the interim, if there is an obvious solution known to others that would short circuit my investigation, I'd be grateful to hear about it.

**Comment by StarAurryon** [comment]
Hello nemasket,

I will try to check this by the end of the week.
By the way, you are not obliged to compile the project yourself, compiled releases are available.

Aurryon

**Comment by nemasket** [comment]
Thanks for the response.  I was so focused on the code aspect that I missed
the release link on the right side.  Thanks for pointing that out.  I'll
give that a twirl tonight.  Maybe there's a repository issue for those
trying the code-centric approach.

Best Regards,
Jurgen

**Comment by StarAurryon** [comment]
I'm closing the bug for now as it is related to the backend that is now hosted on another github repo. If you know people that can help me porting the UI from QT to GTK with gotk4, go ahead, I want to bring back this project to life.
