### ISSUE TITLE
Support automatic patch change while playing backing tracks as with the Boss Pocket GT

### ISSUE THREAD

**Issue by manast** [StarAurryon/lpedit#6]
Yo!

Thank you for giving a try to reverse engineer the HD POD500x. I think this pedal has still a lot of potential but it is going to waste due to Line 6 not giving it all the love it deserves. 
One killer feature would be to be able to synch pedal changes based on a played backing track, much as the new Boss Pocket GT does (https://www.boss.info/us/products/pocket-gt/).
I am mostly interested in knowing your opinion about the feasibility of implementing this feature more than asking you to implement it yourself (I could actually put the effort myself). Basically, it should be just a matter of changing the currently active patch on the Pod programmatically, is this something your current interface allows you to do, or more reverse engineering is needed?

Best regards!.

**Comment by StarAurryon** [comment]
Yes this is definitely possible.

Maybe we could do a fake midi interface that is controlled by another soft doing the track changes. Then it is transmitted to the pod to lpedit. But It would be easier to get an usb to midi cable.

**Comment by manast** [comment]
@StarAurryon do you have any reference that explains how to use an USB to midi cable? I do not fully understand how MIDI works, and I was just thinking that the USB interface of the POD is enough to control all its functions including changing the current instrument.

**Comment by StarAurryon** [comment]
Midi is the defacto music serial interface. It is used from music stuff from Cubase / Protools, to keyboard such as akai MPK Mini. Basically it allow to remote control one device from another : id of the pressed button and the velocity is sent to the device.

If you have a track on Cubase / Ardour / LMMS you can toggle a midi change at a distinct moment.
